version: "3.1"

services:
  db:
    image: cassandra:4.1.3
    restart: always
    volumes:
      - cassandra_data:/var/lib/cassandra

  db_init:
    build:
      context: .
      dockerfile: Dockerfile.db_init
    restart: on-failure
    command: sh -c "/wait && cqlsh -f /db_init.cql"
    environment:
      - CQLSH_HOST=db
      - CQLSH_PORT=9042
      - WAIT_HOSTS=db:9042

      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: sh -c "/wait && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - $PWD/image_vectors.pt:/db/image_vectors.pt
    environment:
      - CASSANDRA_HOST=db
      - CASSANDRA_PORT=9042
      - WAIT_HOSTS=db:9042
      - IMAGE_VECTORS_PATH=/db/image_vectors.pt

      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  cassandra_data:
